version: '2'
services:
    jpr-app:
        image: jpr
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jpr-mysql:3306/jpr?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jpr-mysql:
        extends:
            file: mysql.yml
            service: jpr-mysql
